pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/YOUR_USERNAME/ENSF400_Project.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-app:v1 .'
            }
        }
        stage('Push to Registry') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/']) {
                    sh 'docker tag my-app:v1 username/my-app:v1'
                    sh 'docker push username/my-app:v1'
                }
            }
        }
    }
}
